apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-8qas
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-8qas
    app.kubernetes.io/part-of: tkwch-fix-0075-0055-app
  name: devfile-sample-8qas
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-8qas
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-8qas
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0-25-tenant/tkwch-fix-0075-0055-app/devfile-sample-8qas@sha256:4b70a6852e65073c61c195e684305179e579759f19670bf2ae0ecb8111ac92f9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
